version: "2"

services:

  auth:
    container_name: auth
    image: auth-node
    build:
      context: ./
    volumes:
      - ./var/www/auth

    links:
     - mongo:mongo
    ports:
      - "3090:3090"

  mongo:
    image: mongo:latest
    container_name: auth-mongo
    ports:
      - "27017:27017"
